### ISSUE TITLE
Build workflows to ingest manual corrections

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-knownprojects#157]
- [x] Append the planner added projects to the KPDB: only append projects where `record_id` is not already in the KPDB, and where the `omit` flag is empty/NULL/No/false (ask CP what the value will be) #167 
- [x] Remove and add records based on records in the Correction table
- [x] Apply the new values and geometries from the Correction table  (#167) and shapefile
- [x] Rerun the units_net calculation based on new units_gross and project ID values (#169) 
- [x] Re-calculate the phasing unit counts based on updated units_net  (#170)

**Comment by mgraber** [comment]
See #158.
When appending the planner-added project table, we might need to over-write existing planner-added projects.

**Comment by mgraber** [comment]
Appending planner added projects to KPDB relates to #166

**Comment by mgraber** [comment]
Left to do as of May 14:
+ Add records where field = add in kpdb_corrections
+ Remove records where field = remove in kpdb_corrections
+ Add geometries from shapefile
+ Recalculate phasing unit counts

**Comment by mgraber** [comment]
See #172
