### ISSUE TITLE
Questions to HED

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-knownprojects#229]
## Week of 2021/03/22
- [ ] Should geometry correction happen before spatial clustering?
- [ ] create a sample geometry corrections file #278
> Just checked, all spatial corrections created by mark are obsolete, it's safe to start a new empty file

## Week of 2021/03/15
<details>

- [x] #209: Are the ZAP filters from @SPTKL appropriate? #276 

</details>

## Week of 2021/03/01
<details>

- [x] #230: What boolean flags should we include? What is the logic for these flags?
- [x] #215: Which units field in devDB should get subtracted from the units in matching non-DOB records? Only `classa_net`?
- [x] #215: If we're interested in keeping information about non-classa units, do we need to adjust our devDB filters? These are currently:
```sql
WHERE job_type <> 'Demolition'
AND a.job_status <> '9. Withdrawn'
AND a.classa_net::integer <> 0
AND a.classa_prop::integer > 0
AND NOT (a.job_type = 'Alteration'
AND a.classa_net::integer <= 0)
```
- [x] #236: Can HED review and confirm that the current logic to match and add HousingDB records should stay the same?

</details>
