### ISSUE TITLE
use and move SCA sql scripts from sharepoint/carto to repo build process

### ISSUE THREAD

**Issue by damonmcc** [NYCPlanning/db-knownprojects#399]
## motivations
* after building KPDB, we must run SQL scripts to aggregate data for SCA (School Construction Authority)
* aside from urgent need to produce outputs, we'd like to move this step into the KPDB build process
* Capital Planning's [OneNote doc](https://nyco365.sharepoint.com/sites/NYCPLANNING/cp/_layouts/15/Doc.aspx?sourcedoc={8f26527c-f42c-46be-9e29-d73a7a80586a}&action=view&wd=target%28Untitled%20Section.one%7Ced58a6a1-1f68-43e6-8b83-42dda5a6e985%2FREAD%20ME%20for%20HED%7C3797d982-1fc6-4800-ad3c-d46e5c1e2a8f%2F%29&wdorigin=703) with details
* Data Egnineering's [Sharepoint folder](https://nyco365.sharepoint.com/sites/NYCPLANNING/itd/edm/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2Fsites%2FNYCPLANNING%2Fitd%2Fedm%2FShared%20Documents%2FPROJECTS%2FDATA%20ENGINEERING%2FKPDB&FolderCTID=0x0120001114839845564543AB5C3DCB09500AC5) with SCA sql scripts

## todos
- [x] use existing scripts and process to produce outputs
  - [x] upload KPDB outputs to carto (Max)
  - [x] run script 5a (Max)
  - [x] run script 5c (Finn)
  - [x] run script 5d (Damon)
- [x] Add scripts to KPDB repo 
- [x] review and share outputs
- [x] scope work of moving this step into the KPDB build process
